version: 0.2
env:
  parameter-store:
    DOCKER_USER: "docker.instanacicd.user"
    DOCKER_PASSWORD: "docker.instanacicd.pass"

phases:
  install:
    runtime-versions:
      golang: 1.16
        #      docker: 19
    commands:
      - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
      - make deps
  build:
    commands:
      - make all publish
    finally:
      - bash -c "bash <(curl -s https://codecov.io/bash)"
