apiVersion: apps/v1
kind: Deployment
metadata:
  name: promep
  labels:
    app: promep
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  selector:
    matchLabels:
      app: promep
  template:
    metadata:
      labels:
        app: promep
    spec:
      containers:
      - name: promep
        image: nfinstana/promep
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
