apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iowait
spec:
  selector:
      matchLabels:
        name: iowait
  template:
    metadata:
      labels:
        name: iowait
    spec:
      containers:
      - image: nfinstana/iowait
        name: iowait
      hostPID: true
