apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: envchecker
  namespace: instana-agent
  labels:
    app: envchecker
spec:
  selector:
    matchLabels:
      name: envchecker
  template:
    metadata:
      labels:
        name: envchecker
    spec:
      hostNetwork: true
      containers:
        - name: envchecker
          image: instana/envcheck-daemon:latest
          imagePullPolicy: Always
          env:
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODEIP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ADDRESS
              value: 0.0.0.0:42700
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 100m
              memory: 512Mi
